version: "3"

services:
    forgejo:
        image: codeberg.org/forgejo/forgejo:1.19.0-2
        container_name: forgejo
        restart: always
        networks:
            - forgejo
        env_file:
            - /home/git/.env.forgejo
        volumes:
            - ./forgejo:/data
            - /home/git/.ssh:/data/git/.ssh
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 3000:3000
            - 222:22
        depends_on:
            - db

    db:
        image: postgres:15
        restart: always
        env_file:
            - /home/git/.env.forgejo
        networks:
            - forgejo
        volumes:
            - ./postgres:/var/lib/postgresql/data

networks:
    forgejo:
        external: false
